name: Run test cases
on:
  workflow_call:

jobs:
  run-test-cases:
    runs-on: ubuntu-latest
    steps:
      - name: Action Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
            node-version: 22.11.0
            cache: 'npm'
            cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Check Test Cases
        run: npm run test