name: Check Dependency
on:
  workflow_call:

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Action Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
            node-version: 22.11.0
            cache: 'npm'
            cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Audit and Fix vulnerabilies
        run: npm audit fix --force
        continue-on-error: true 