name: Push to ECR
on: 
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Tag of the Docker Image'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  check-dependencies:
    uses: iorikaze/startbootstrap-resume/.github/workflows/check-dependency.yaml@master

  check-test-cases:
    needs: check-dependencies
    uses: iorikaze/startbootstrap-resume/.github/workflows/check-test-cases.yaml@master

  create-docker-image:
    needs: check-test-cases
    runs-on: ubuntu-latest

    steps:
      - name: Action Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - run: npm run build

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ap-southeast-1
          
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          provenance: true

      - name:  Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: iorikaze-ecr-repo
          IMAGE_TAG: ${{ inputs.image-tag }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG